### ISSUE TITLE
Include git-mob in open-vsx extension repository

### ISSUE THREAD

**Issue by rainbyte** [rkotze/git-mob-vs-code#122]
## Summary

This extension could be included in [open-vsx extension repository](https://open-vsx.org/)

## Motivation

VSCode Marketplace is only available from Microsoft VSCode builds.

Code-OSS and VSCodium builds don't have access to Marketplace.

Every build, propietary or fully open-source, can access [open-vsx](https://open-vsx.org/).

## Describe alternatives you've considered

Extension could be loaded via vsix file, but it is cumbersome.

## Additional context

[open-vsx](https://open-vsx.org/) extensions automatically appear in Code-OSS and VSCodium extension manager searchs.

**Comment by rkotze** [comment]
Hi @rainbyte 

Thanks for raising this. I think this will be a good one to take on and will put it on the to-do list.

**Comment by rkotze** [comment]
I've published it to the (open VSX registry)[https://open-vsx.org/extension/RichardKotze/git-mob]. Please try it out and share it with others.
