### ISSUE TITLE
Open git-coauthors file from sidebar doesn't work on Windows

### ISSUE THREAD

**Issue by r15ch13** [rkotze/git-mob-vs-code#21]
### Prerequisites

- [X] [Checked that your issue isn't already filed][git-mob-vs-code issues]
- [X] Tried upgrading to the latest git-mob-vs-code and git-mob version (`npm i -g git-mob`)
- [X] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob-vs-code issues]: https://github.com/rkotze/git-mob-vs-code/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description
Clicking the `Open git-coauthors file` button in the sidebar results in an error.
The replace regex in [git-mob-coauthors-file.js#L13](https://github.com/rkotze/git-mob-vs-code/blob/893549652f6455396c3df7ca7099b2eca3c0a58c/src/git-mob-coauthors-file.js#L13) removes the drive letter which results in wrong path.
`file:///Users/r15ch/.git-coauthors` or `\Users\r15ch\.git-coauthors`

### Steps to Reproduce

1. On Windows 10 using VSCode Portable
2. Click `Open git-coauthors file` button

**Expected behaviour:** [What you expect to happen]
Should open `.git-coauthors` file

**Actual behaviour:** [What actually happens]
![image](https://user-images.githubusercontent.com/432127/65510195-a689ea00-ded4-11e9-9dcb-78c482756a3e.png)

### Versions

- operating system and version: Windows 10
- git-mob-vs-code version (can be found in the Extensions tab): 1.1.1
- git-mob version (`git-mob --version`): 1.0.1
- git version (`git --version`): 2.20.1.windows.1

**Comment by rkotze** [comment]
Interesting, I specifically remove the drive letter to make ti work on Windows 

- [Commit](https://github.com/rkotze/git-mob-vs-code/commit/4bbc868daebe3bd2f9b4978330131092c67bf4fb)
- [Current test file](https://github.com/rkotze/git-mob-vs-code/blob/master/src/git-mob-coauthors-file.spec.js)

I think the difference being you run the portable VS code version. I wonder if that has anything to do with it.
I'll try to find time to investigate it.

**Comment by rkotze** [comment]
@r15ch13 I've setup Git Mob on a portable version of VS Code and was able to open the `.git-coauthors` file.

Where you able to follow the path in the error message to the file? I'm just wondering if the path is incorrect? By chance are you using the environment variable `GITMOB_COAUTHORS_PATH`?

**Comment by r15ch13** [comment]
The path itself is correct, except the missing drive letter. `GITMOB_COAUTHORS_PATH` is not set.

It works just fine if I remove `.replace(/^([a-z]:[\\]|[\/])/gi, "")` from
https://github.com/rkotze/git-mob-vs-code/blob/f43599280b33b9e6e7b7cf52974f1866d2b4b22d/src/git-mob-coauthors-file.js#L18

**Comment by r15ch13** [comment]
Example output after adding test output.
![image](https://user-images.githubusercontent.com/432127/66426583-74b76e00-ea12-11e9-978b-96aea17ddb64.png)


```js
  get path() {

    vscode.window.showErrorMessage("without regex: " + path.join(os.homedir(), this.file));
    vscode.window.showErrorMessage("with regex: " + path.join(os.homedir(), this.file).replace(/^([a-z]:[\\]|[\/])/gi, ""));

    return path
      .join(os.homedir(), this.file);
  }
```

**Comment by rkotze** [comment]
Interesting, I'm on windows 10 and used the latest version of git-mob, git-mob-vs-code and VS Code.

The only thing I don't know is what version of VS Code do you have?

As far as I understand Portable VS Code, it does **not** auto-update. Maybe that version does not support file paths in the same way as the latest.

**Comment by r15ch13** [comment]
![image](https://user-images.githubusercontent.com/432127/66466775-8be27400-ea83-11e9-97a6-593f30e2c704.png)

Installed via [Scoop](https://github.com/lukesampson/scoop/) to `D:\scoop\apps\vscode-portable\current`

**Comment by rkotze** [comment]
I see, the issue could be that is looking for .git-coauthors on your D drive but it's on your C drive.

This is easy to fix for windows, just need to think about Unix based systems.

**Comment by r15ch13** [comment]
Shouldn't be `os.homedir()` enough? The directory separators are correct in both cases.

```js
const os = require('os')
const path = require('path')

console.log(path.join(os.homedir(), '.git-coauthors'))
```

![image](https://user-images.githubusercontent.com/432127/66470170-5b9dd400-ea89-11e9-9406-766a45ffacb0.png)
Test in Ubuntu WSL

**Comment by rkotze** [comment]
I remember the issue was on a Mac. So I'll need to confirm the path on a Mac.

When I first did this, I thought `os.homedir()` was the solution.

**Comment by rkotze** [comment]
I've tried it on MAC OS and works fine. So there is no need to remove the drive letter.
I'll get this fix out soon.

**Comment by rkotze** [comment]
Will be part of release 1.3
