### ISSUE TITLE
Cannot read properties of undefined (reading 'email')

### ISSUE THREAD

**Issue by Zaczero** [rkotze/git-mob-vs-code#344]
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob-vs-code issues]
- [ ] Tried upgrading to the latest git-mob-vs-code and git-mob version (`npm i -g git-mob`)
- [ ] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob-vs-code issues]: https://github.com/rkotze/git-mob-vs-code/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

On VSCode startup, I receive the "Cannot read properties of undefined (reading 'email')" error. The extension used to work just fine but suddenly stopped one day.

![image](https://github.com/user-attachments/assets/4674f23f-79bc-4bf2-8ad8-8d522b21f13b)

### Steps to Reproduce

1. Start VSCode

**Expected behaviour:** Works

**Actual behaviour:** Doesn't work

**Reproduces how often:** 100%

### Versions

- operating system and version:
- VS Code version 1.92.1
- git-mob-vs-code version (can be found in the Extensions tab) 1.20.1
- git version (`git --version`): 2.44.1

### Additional Information

![image](https://github.com/user-attachments/assets/5f80d825-1e3c-49ba-933a-a2a80f3acbf5)

```txt
[Extension Host] SETUP ERROR:  TypeError: Cannot read properties of undefined (reading 'email')
    at /home/user/.vscode/extensions/richardkotze.git-mob-1.20.1/src/build-co-author-groups.js:26:48
    at Array.filter (<anonymous>)
    at resolveAuthorLists (/home/user/.vscode/extensions/richardkotze.git-mob-1.20.1/src/build-co-author-groups.js:26:18)
    at buildCoAuthorGroups (/home/user/.vscode/extensions/richardkotze.git-mob-1.20.1/src/build-co-author-groups.js:41:3)
    at bootGitMob (/home/user/.vscode/extensions/richardkotze.git-mob-1.20.1/src/setup-git-mob.js:41:51)
```

**Comment by Zaczero** [comment]
Turns out my git configuration was messed up. Perhaps the error message could be slightly more intuitive? Otherwise, feel free to close the issue :+1:.

**Comment by rkotze** [comment]
Hi @Zaczero 

Glad you fixed the issue.

Improving the error message does sound useful but it will be a while before I get to look at it.
You are welcome to contribute to add better error handling?
