### ISSUE TITLE
Right icon persist "-" (minus) after running `git commit` when `gitMob.postCommit.solo: true`

### ISSUE THREAD

**Issue by kdnk** [rkotze/git-mob-vs-code#380]
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob-vs-code issues]

[git-mob-vs-code issues]: https://github.com/rkotze/git-mob-vs-code/issues?utf8=%E2%9C%93&q=is%3Aissue

### Steps to Reproduce

1. Settings have postCommit solo set to true
2. Select a co-author for commit
3. Commit changes

**Expected behaviour:** Return co-author to unselected with add action (plus symbol)

**Actual behaviour:** Co-author returned to unselected but keeps removed actions (minus symbol)

**Reproduces how often:** 100%

### Additional Information

![CleanShot 2024-11-21 at 10 42 55@2x](https://github.com/user-attachments/assets/d75cfc76-7447-47d2-aa07-3a25f69e95f4)

**Comment by rkotze** [comment]
@kdnk thanks for reporting this bug. I've got a fix for this.

**Comment by kdnk** [comment]
@rkotze Thank you!

**Comment by rkotze** [comment]
Released in version [v1.21.1](https://github.com/rkotze/git-mob-vs-code/tree/v1.21.1)
