### ISSUE TITLE
Cannot read property 'inputBox' of undefined

### ISSUE THREAD

**Issue by rkotze** [rkotze/git-mob-vs-code#48]
### Description

When selecting a co-author an error appears "Cannot read property 'inputBox' of undefined".

This is an issue in the latest release of VS Code 1.51

Related bugs in VS Code logged which might fix the issue

- https://github.com/microsoft/vscode/issues/108046 
- https://github.com/microsoft/vscode/issues/104629

### Steps to Reproduce

1. Click the plus button to select a co-author
2. Error appears and unselected co-authors disappear

**Expected behaviour:**

Update SCM input box with the selected co-author, selected co-authors stay and no error alert shows.

**Actual behaviour:**

The error appears and unselected co-authors disappear.

**Reproduces how often:** 

For one Git repositories 95% of the time.

Multiple repositories, as long as you have one selected the issue does not appear. However, when you click in the input box it becomes unselected and the error appears.

### Mitigation 

Reloading the whole of VS Code mitigates the issue as long as you don't interact with the SCM at all.

### Versions

- mac OS Catalina
- git-mob-vs-code version 1.10.0
- git-mob version 1.1.0
- git version 2.24.3

**Comment by rkotze** [comment]
Successfully deployed 1.10.1

**Comment by ORiveraJr84** [comment]
I'm still having this same issue. Has a resolution been found?
