### ISSUE TITLE
Search for co-authors does not return results

### ISSUE THREAD

**Issue by ethanstrominger** [rkotze/git-mob-vs-code#50]
### Prerequisites

- [X] [Checked that your issue isn't already filed][git-mob-vs-code issues]
- [X] Tried upgrading to the latest git-mob-vs-code and git-mob version (`npm i -g git-mob`)
- [X] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob-vs-code issues]: https://github.com/rkotze/git-mob-vs-code/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

No github users appear when I try to search for them

### Steps to Reproduce

1. Select "Search for co-authors on Github"
2. Type in any letters (Ben)
3. Nobody appears, even if I press Enter

**Expected behaviour:** A list of github users that match the letters typed in should appear

**Actual behaviour:** Nothing

**Reproduces how often:** [What percentage of the time does it reproduce?] Always

A related issue I cannot reproduce now: Initially, even search using the search icon under more co-authors returned nothing.

### Versions

- operating system and version:
- git-mob-vs-code version (can be found in the Extensions tab)
- git-mob version (`git-mob --version`):
- git version (`git --version`):

**Comment by rkotze** [comment]
Just want to check if you provided a GitHub PAT in Git Mob settings which is needed to search GitHub and extract emails?

https://github.com/rkotze/git-mob-vs-code#github---personal-access-token

**Comment by ethanstrominger** [comment]
@rkotze I had not added the PAT.  I will add another issue to make that more obvious.
