### ISSUE TITLE
UI: Make it more obvious what happens when you click on somebody's name in the search list

### ISSUE THREAD

**Issue by ethanstrominger** [rkotze/git-mob-vs-code#51]
## Summary

When you click on Search next to More co-authors and you click on somebody's name, it puts that person in the Unselected group.  However, that is not obvious.  It would be good to add some help text in the list like "Select a person to move to the Unselected list."  I have been using for a while before  I figured that out.  Alternatively, filter the "More co-authors" list in the "More co-authors" pane.

## Motivation

Make the application more intuitive.

## Describe alternatives you've considered

Display a message after someone is selected "Added to unselected list".

**Comment by rkotze** [comment]
I'm open to ideas to make this more intuitive. 

Out of interest what behaviour did you expect when selecting a user in the search list?

**Comment by ethanstrominger** [comment]
Creating new proposal

**Comment by rkotze** [comment]
I'm happy to keep this and refine the idea further.

**Comment by ethanstrominger** [comment]
@rkotze New proposal covers this and more.
