### ISSUE TITLE
Add Search to Unselected list.

### ISSUE THREAD

**Issue by ethanstrominger** [rkotze/git-mob-vs-code#53]
## Summary

Add a search option for the Unselected list, like the More Authors option.

## Motivation

Make it easier to use when lots of people in the Unselected List.

**Comment by rkotze** [comment]
Yes, I think this would be an edge case but still think it would be useful to have.

I'm thinking it would be useful to combine the lists "more authors" & "unselected" into one when searching and selecting. This would make it a less clunky flow.

For example:

If you search and select a user that is in the "more authors" list it would add them into "co-authoring".

**Comment by ethanstrominger** [comment]
Creating new proposal

**Comment by rkotze** [comment]
@ethanstrominger  No need to create new issues we can just modify these. It's useful to keep the change history and review decisions.

**Comment by ethanstrominger** [comment]
@rkotze New proposal does away with Unselected list, so it is N/A
