### ISSUE TITLE
Error message if Github PAT not entered or if no results

### ISSUE THREAD

**Issue by ethanstrominger** [rkotze/git-mob-vs-code#58]
## Summary

When you try to search an entire github repository, give an error if the Personal Access Token has not been set.  "Personal Access Token has not been set.  Create a Personal Access Token with User:Read access, if not already done.  Set the Personal Access Token for Github Co-authors."

If no records returned, display error message
"No records found.  Check the name and confirm the Personal Access Token setting is correct and the token has User:Read privilege."

## Motivation

Better user experience

## Describe alternatives you've considered

Checking if the Personal Access token has User:Read privileges if no users found and tailor message based on that.  I don't think that is worth the effort.

**Comment by rkotze** [comment]
An error message will appear saying you need a GitHub PAT after you try entering a name, as a toast popup on the bottom right (not too obvious). But I agree this can be improved and show the permissions required.

Another option would be to look into changing the approach using [`vscode.authentication`](https://code.visualstudio.com/api/references/vscode-api#authentication) then it's easy to manage the permissions `user:read`

Found an example class here: [vscode-pull-request-github](https://github.com/microsoft/vscode-pull-request-github/blob/9fb85eccb24f738c3288398691d931e990d4d117/src/github/credentials.ts#L35)

btw: this searches the whole of GitHub, not the current repository.

**Comment by ethanstrominger** [comment]
@rkotze Making the error message more obvious would be sufficient.  Sounds though like with the class, it would not be an issue?

**Comment by rkotze** [comment]
@ethanstrominger I think we can make this issue about a more visible error message. Something that shows up before typing in search criteria.

The authorisation class can be moved to a new issue, more as an alternative/nice to have feature.

**Comment by rkotze** [comment]
Added in v1.12.0
