### ISSUE TITLE
Cannot read property 'inputBox' of undefined for workspaces

### ISSUE THREAD

**Issue by ORiveraJr84** [rkotze/git-mob-vs-code#80]
### Description

Able to reproduce the issue and I have written how to reproduce the bug for later reference. From @rkotze 

When using workspaces and having multiple repos open an error appears on load of the panel and when applying co-authors.

### Steps to Reproduce

1. Open multiple projects into one instance of VS Code
2. Error will appear on load
3. Can see a list of co-authors but all the error shows when trying to apply co-authors

**Expected behaviour:**

No error dialogue and co-authors applied to the input box

**Actual behaviour:**

Error dialogue shows and nothing changes in UI. Co-author not applied to the input box.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

- operating system and version: `Mac OS`
- VS Code version `1.62.2`
- git-mob-vs-code version `1.14.0`
- git version (`git --version`) `2.24.3`

**Comment by ORiveraJr84** [comment]
Already posted by another user. Disregard issue.

**Comment by rkotze** [comment]
@ORiveraJr84 I think it's best to reopen this issue and provide the information to reproduce it.

The other issue you comment on is closed and not pursuing.

**Comment by rkotze** [comment]
Fixed in version `1.14.1`
